Test results.log

diff --git a/.github/workflows/backend-ci.yaml b/.github/workflows/backend-ci.yaml
--- a/.github/workflows/backend-ci.yaml
+++ b/.github/workflows/backend-ci.yaml
@@ -30,13 +30,21 @@ jobs:
       run: sudo apt-get install -y jmeter
 
     - name: Run sample_test_script2
-      run: jmeter -n -t ./Sample_test_script2.jmx -l sample_test_script2.jtl
+      run: jmeter -n -t ./Sample_test_script.jmx -l results.log -e -o ./results/
     
-    - name: Verify test results
-      run: cat sample_test_script2.jtl
+    - name: Archive results.log file and upload to GitHub
+      uses: actions/upload-artifact@v2
+      with:
+        name: results
 
     - name: Make sure test passed
-      run: grep -q "false" sample_test_script2.jtl && exit 1 || exit 0
+      run: |
+        if grep -q "false" results.log; then
+          echo "Test failed"
+          exit 1
+        else
+          echo "Test passed"
+        fi
     
     - name: Stop docker compose
       run: docker-compose -f docker-compose.yml down
